### ISSUE TITLE
Error on line 633:33: Invalid canvas size: -3.1839999999999997 by 18.0

### ISSUE THREAD

**Issue by VGbranix** [DrieStone/TeslaData-Widget#8]
I am not allowed to use iCloud on my iPhone. I did a manual install, replaced all FileManager.iCloud with FileManager.local, (added the TeslaFi API link) and I receive the following error:

> Error on line 633:33: Invalid canvas size: -3.1839999999999997 by 18.0

Any further thoughts?

**Comment by VGbranix** [comment]
Figured out that my car was sleeping, and TeslaFi did not return proper valid data for the widget unless queried for:
> JSON output of last data point with charge data - https://www.teslafi.com/feed.php?token=TOKEN&command=lastGood

So, if your vehicle is sleeping, add make sure you add your token, as well as '&command=lastGood' to get valid data.

**Comment by DrieStone** [comment]
There should have been a "lastGood" if you just provide the API key. I've taken a bit of a pause on this until the new year. I'll make sure I add a non-iCloud option in the future.

Thanks!
